### ISSUE TITLE
Pre-C99 compilation failure

### ISSUE THREAD

**Issue by adr26** [pythoncapi/pythoncapi_compat#11]
Unfortunately, building fails with MSVC in pre-C99 mode (compiling against Python 2.7):
```
c:\temp\bitarray\bitarray\pythoncapi_compat.h(264) : error C2143: syntax error : missing ';' before 'type'
c:\temp\bitarray\bitarray\pythoncapi_compat.h(265) : error C2065: 'res' : undeclared identifier
c:\temp\bitarray\bitarray\pythoncapi_compat.h(268) : error C2065: 'res' : undeclared identifier
```
Hopefully #10 is an uncontroversial fix!

Thanks, Andrew R

**Comment by vstinner** [comment]
Fixed by https://github.com/pythoncapi/pythoncapi_compat/commit/920f2ff39a7a82a52cab18109cc83922bce3a28b Thanks for the fix!
