### ISSUE TITLE
Compilation errors on windows for Python 2.7 on AppVeyor

### ISSUE THREAD

**Issue by icemac** [pythoncapi/pythoncapi_compat#16]
Integrating `pythoncapi_compat.h` in https://github.com/zopefoundation/ExtensionClass/pull/38 gives the following error on AppVeyor for Python 2.7.

```
   C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Isrc -Ic:\python27\include -Ic:\python27\PC /Tcsrc\ExtensionClass\_ExtensionClass.c /Fobuild\temp.win32-2.7\Release\src\ExtensionClass\_ExtensionClass.obj
73    _ExtensionClass.c
74    c:\projects\extensionclass\src\extensionclass\pythoncapi_compat.h(272) : error C2143: syntax error : missing ';' before 'type'
75    c:\projects\extensionclass\src\extensionclass\pythoncapi_compat.h(277) : error C2065: 'use_tracing' : undeclared identifier
76    c:\projects\extensionclass\src\extensionclass\pythoncapi_compat.h(285) : error C2143: syntax error : missing '{' before '*'
77    c:\projects\extensionclass\src\extensionclass\pythoncapi_compat.h(288) : warning C4133: 'return' : incompatible types - from 'PyObject *' to 'int *'
78    error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

The definitions on these lines are not used in the package, so I could delete them – is there any other solution?

**Comment by vstinner** [comment]
Hi, does my commit 359a6804ebdad9a9388736cf19f718d9b148643c fix all issues? I don't know how to test pythoncapi_compat on Python 2.7 on Windows. My attempt didn't work: https://github.com/pythoncapi/pythoncapi_compat/pull/17

**Comment by icemac** [comment]
zopefoundation/ExtensionClass#38 no longer uses `pythoncapi_compat.h`, so I am also unable to verify. I saw the error on AppVeyor.

**Comment by vstinner** [comment]
I consider that my fix is enough. I don't know how to test it. If someone still has an issue with Python 2.7 on Windows, please open  a new issue (or comment this one).
